services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    restart: unless-stopped

    prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped

      # network_mode: host
    pid: host

    volumes:
      - "/:/host:ro,rslave"

    command:
      - "--path.rootfs=/host"
